name: AWS RUM Web Client Continuous Build

on:
    push:
        branches: [main, release/*.*.*]
    pull_request:
        branches: [main, release/*.*.*]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    unit-test:
        name: Check Format and Run Unit Tests
        runs-on: ubuntu-20.04
        permissions: read-all
        steps:
            - name: Checkout AWS RUM Web Client Repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '16.x'

            - name: Cache NPM modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - run: npm ci

            - name: Check Code Format
              run: npx prettier --check .

            - name: Run Linter
              run: npm run lint:errors

            - name: Run Unit Tests
              run: npm run test

    integ-test:
        name: Run Integ Tests on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        permissions: read-all
        env:
            NODE_OPTIONS: --max-http-header-size=80000
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-20.04, windows-latest]

        steps:
            - name: Checkout AWS RUM Web Client Repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '16.x'

            - name: Cache NPM modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - run: npm ci

            - name: Run Integ Tests on ubuntu-20.04
              if: matrix.os == 'ubuntu-20.04'
              run: |
                  npm run integ:headless-linux

            - name: Run Integ tests on windows-latest
              if: matrix.os == 'windows-latest'
              run: |
                  npm run integ:headless-windows
