name: AWS RUM Web Client Continuous Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    unit-test:
        name: Check Format and Run Unit Tests
        runs-on: ubuntu-latest
        permissions: read-all
        steps:
            - name: Checkout AWS RUM Web Client Repository
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'

            - name: Cache NPM modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - run: npm ci

            - name: Check Code Format
              run: npm run prettier

            - name: Run Linter
              run: npm run lint

            - name: Run Unit Tests
              run: npm run test

    integ-test:
        name: Run Integ Tests on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        permissions: read-all
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout AWS RUM Web Client Repository
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'

            - name: Cache NPM modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - run: npm ci

            - name: Run Integ Tests on ubuntu-latest
              if: matrix.os == 'ubuntu-latest'
              env:
                  NODE_OPTIONS: --max-http-header-size=80000
              run: |
                  npm run integ:local:chrome:headless
                  npm run integ:local:firefox:headless

            - name: Run Integ tests on windows-latest
              if: matrix.os == 'windows-latest'
              env:
                  NODE_OPTIONS: --max-http-header-size=80000
              run: |
                  npm run integ:local:ie
                  npm run integ:local:edge
                  npm run integ:local:firefox
                  npm run integ:local:chrome
